spring:
  datasource:
    url: jdbc:postgresql://dpg-d4mrqdkhg0os73c3pt00-a.oregon-postgres.render.com:5432/onlinebusdb_8pl8
    username: onlinebusdb_8pl8_user
    password: qhvau5oLkvSQcizA3VHMC5bvYIlSWK3x

  profiles:
    active: dev

  jackson:
    serialization:
      indent_output: true

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

app:
  pagination:
    default-page: 0
    default-size: 10
    max-size: 100

  mail:
    host: smtp.gmail.com
    port: 587
    username: guguu957@gmail.com
    password: dqrz qrjd byxm hwqq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml

mybatis.type-aliases-package: com.xypha.OnlineBus.Buses.Entity

